const ALL_YEAR = {
  bestMonths: [3, 4, 5, 6, 7, 8, 9, 10],
  acceptableMonths: [1, 2, 11, 12],
  unsuitableMonths: [],
};

const ROUTE_IMAGE_BASE = import.meta.env?.BASE_URL ?? "/europe-travel-selector/";
const localRouteImage = (filename) => `${ROUTE_IMAGE_BASE}route-images/${filename}`;

const weekendRoute = (route) => ({
  parentCategory: "Land",
  countries: ["United Kingdom"],
  minimumDurationDays: 2,
  idealDurationDays: 2,
  maximumDurationDays: 3,
  travelStyles: ["weekend"],
  budgetMinGBP: 120,
  budgetTypicalGBP: 230,
  budgetMaxGBP: 420,
  budgetBasis: "Per person, twin-share, including return transport and two nights (planning estimate)",
  budgetConfidence: "low",
  departureCities: ["Manchester"],
  directFromManchester: "yes",
  ManchesterAccessScore: 8,
  flightRequired: false,
  trainPossible: true,
  ferryPossible: false,
  cruiseBased: false,
  drivingRequired: false,
  overnightTravelPossible: false,
  overnightTravelRequired: false,
  typicalTransferLevel: "low",
  hotelChanges: "none",
  physicalEffort: 2,
  walkingLevel: 2,
  stairsRisk: 2,
  luggageHandling: 1,
  comfortLevel: 4,
  weatherRisk: 2,
  suitableForSolo: true,
  suitableForCouple: true,
  suitableForFriends: true,
  suitableForFamily: true,
  suitableForOlderTraveller: true,
  suitableForMum: true,
  natureScore: 4,
  sceneryScore: 6,
  cultureScore: 7,
  historyScore: 7,
  foodScore: 7,
  relaxationScore: 7,
  adventureScore: 3,
  photographyScore: 7,
  uniqueTransportScore: 2,
  valueForMoneyScore: 8,
  onceInALifetimeScore: 3,
  revisitScore: 8,
  tags: ["weekend", "no-fly"],
  isManchesterWeekendRoute: true,
  weekendPlanningEstimate: true,
  localConnectionsRequired: false,
  carDependency: "unnecessary",
  fridayEveningFeasible: true,
  saturdayMorningFeasible: true,
  sundayEveningReturnFeasible: true,
  liveVerificationNeeded: true,
  estimated: true,
  sourceSection: "Manchester Weekend official-source research",
  ...ALL_YEAR,
  ...route,
  officialSources: [{ label: route.officialSourceName, url: route.officialSourceUrl }],
  drawbacks: [route.mainLogisticalDrawback],
});

export const MANCHESTER_WEEKEND_ROUTES = [
  weekendRoute({
    id: "man-weekend-liverpool", routeName: "Liverpool Waterfront & Cultural Quarter", shortName: "Liverpool",
    minimumDurationDays: 1, idealDurationDays: 2, maximumDurationDays: 3, travelStyles: ["day-trip", "weekend"],
    imageUrl: localRouteImage("liverpool-waterfront.svg"), imageAlt: "Stylised Liverpool waterfront with dock buildings and the River Mersey at sunset", imageCredit: "Original local illustration",
    routeBase: "Liverpool", region: "Liverpool City Region", routeType: "City and culture", weekendRouteType: "City and culture", tripTypes: ["City Break", "Culture"],
    mainStops: ["Royal Albert Dock", "Waterfront", "Georgian Quarter"], description: "A compact rail-first city weekend combining the waterfront, museums and central neighbourhoods.",
    highlights: ["Royal Albert Dock and waterfront", "National museums", "Walkable cultural quarters"], mainLogisticalDrawback: "Major events can make central hotels expensive.",
    officialSourceName: "VisitLiverpool", officialSourceUrl: "https://www.visitliverpool.com/", evidenceNote: "The official destination site groups substantial central attractions within a compact city-break base reached directly from Manchester.",
    manchesterJourneyTime: { minHours: 0.75, maxHours: 1.25, label: "45–75 minutes", estimateBasis: "Typical direct rail planning band", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 1, likelyTransportMode: "Direct train", directConnectionStatus: "direct", majorTransferCountToBase: 0, weekendSuitability: 10, weekendSuitabilityEvidence: "Very short direct journey and fully usable Friday-to-Sunday window.",
    ManchesterAccessScore: 10, budgetMinGBP: 100, budgetTypicalGBP: 190, budgetMaxGBP: 340, cultureScore: 9, historyScore: 8, foodScore: 8,
  }),
  weekendRoute({
    id: "man-weekend-chester", routeName: "Roman Chester & River Dee", shortName: "Chester",
    minimumDurationDays: 1, idealDurationDays: 2, maximumDurationDays: 3, travelStyles: ["day-trip", "weekend"],
    routeBase: "Chester", region: "Cheshire", routeType: "Heritage city", weekendRouteType: "Heritage city", tripTypes: ["City Break", "History"],
    mainStops: ["City Walls", "The Rows", "River Dee"], description: "A low-complexity heritage weekend based around Chester's walls, Rows and riverside.",
    highlights: ["Complete city-wall circuit", "The Rows", "River Dee promenade"], mainLogisticalDrawback: "The wall circuit includes steps, though street-level alternatives exist.",
    officialSourceName: "Visit Cheshire – Chester", officialSourceUrl: "https://visitcheshire.com/locations/chester", evidenceNote: "The official destination page presents Chester as a concentrated heritage base suitable for a two-night visit.",
    manchesterJourneyTime: { minHours: 1, maxHours: 1.5, label: "1–1½ hours", estimateBasis: "Conservative direct rail band", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 1.25, likelyTransportMode: "Direct train", directConnectionStatus: "direct", majorTransferCountToBase: 0, weekendSuitability: 9, weekendSuitabilityEvidence: "Direct journey, compact centre and flexible Sunday return.",
    ManchesterAccessScore: 9, budgetMinGBP: 110, budgetTypicalGBP: 210, budgetMaxGBP: 360, historyScore: 10, walkingLevel: 3, stairsRisk: 3,
  }),
  weekendRoute({
    id: "man-weekend-york", routeName: "York Walls, Minster & Museums", shortName: "York",
    minimumDurationDays: 1, idealDurationDays: 2, maximumDurationDays: 4, travelStyles: ["day-trip", "weekend", "short-break"],
    imageUrl: localRouteImage("york-minster.svg"), imageAlt: "Stylised view of York Minster rising above historic rooftops and the city walls", imageCredit: "Original local illustration",
    routeBase: "York", region: "North Yorkshire", routeType: "Heritage city", weekendRouteType: "Heritage city", tripTypes: ["City Break", "History"],
    mainStops: ["York Minster", "City Walls", "Museum Gardens"], description: "A direct-rail heritage weekend with enough central sights for either two or three days.",
    highlights: ["York Minster", "Medieval streets and walls", "Railway and city museums"], mainLogisticalDrawback: "Popular weekends require advance hotel and attraction booking.",
    officialSourceName: "Visit York", officialSourceUrl: "https://visityork.org/explore", evidenceNote: "Visit York's official guide supports a dense, walkable itinerary from a single central base.",
    manchesterJourneyTime: { minHours: 1.25, maxHours: 1.75, label: "1¼–1¾ hours", estimateBasis: "Typical direct rail planning band", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 1.5, likelyTransportMode: "Direct train", directConnectionStatus: "direct", majorTransferCountToBase: 0, weekendSuitability: 10, weekendSuitabilityEvidence: "Frequent direct access and strong two-day itinerary depth.",
    ManchesterAccessScore: 10, budgetMinGBP: 140, budgetTypicalGBP: 270, budgetMaxGBP: 460, historyScore: 10, cultureScore: 9, walkingLevel: 3,
  }),
  weekendRoute({
    id: "man-weekend-leeds", routeName: "Leeds Culture, Arcades & Waterfront", shortName: "Leeds",
    minimumDurationDays: 1, idealDurationDays: 2, maximumDurationDays: 3, travelStyles: ["day-trip", "weekend"],
    routeBase: "Leeds", region: "West Yorkshire", routeType: "City and culture", weekendRouteType: "City and culture", tripTypes: ["City Break", "Culture"],
    mainStops: ["Victorian Arcades", "Civic Quarter", "Waterfront"], description: "A fast direct-rail city break centred on galleries, arcades, food and the waterfront.",
    highlights: ["Historic shopping arcades", "Free central museums", "Food and waterfront districts"], mainLogisticalDrawback: "Nightlife-heavy areas may not suit travellers seeking a quiet stay.",
    officialSourceName: "Visit Leeds", officialSourceUrl: "https://www.visitleeds.co.uk/things-to-do/", evidenceNote: "The official city guide shows enough closely grouped culture and food attractions for a weekend without a car.",
    manchesterJourneyTime: { minHours: 0.75, maxHours: 1.25, label: "45–75 minutes", estimateBasis: "Typical direct rail planning band", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 1, likelyTransportMode: "Direct train", directConnectionStatus: "direct", majorTransferCountToBase: 0, weekendSuitability: 9, weekendSuitabilityEvidence: "Short direct journey and no local transport dependency.",
    ManchesterAccessScore: 10, budgetMinGBP: 100, budgetTypicalGBP: 200, budgetMaxGBP: 360, cultureScore: 9, foodScore: 9,
  }),
  weekendRoute({
    id: "man-weekend-sheffield", routeName: "Sheffield Culture & Urban Green Space", shortName: "Sheffield",
    minimumDurationDays: 1, idealDurationDays: 2, maximumDurationDays: 3, travelStyles: ["day-trip", "weekend"],
    routeBase: "Sheffield", region: "South Yorkshire", routeType: "City and green space", weekendRouteType: "City and green space", tripTypes: ["City Break", "Culture", "Nature"],
    mainStops: ["Winter Garden", "Millennium Gallery", "Kelham Island"], description: "A quick rail weekend mixing central culture, industrial heritage and accessible urban green space.",
    highlights: ["Winter Garden", "Millennium Gallery", "Kelham Island heritage"], mainLogisticalDrawback: "Sheffield's hills can add effort between neighbourhoods.",
    officialSourceName: "Welcome to Sheffield", officialSourceUrl: "https://www.welcometosheffield.co.uk/home", evidenceNote: "The official destination site combines central attractions and neighbourhood itineraries appropriate to a short rail break.",
    manchesterJourneyTime: { minHours: 0.75, maxHours: 1.25, label: "45–75 minutes", estimateBasis: "Typical direct rail planning band", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 1, likelyTransportMode: "Direct train", directConnectionStatus: "direct", majorTransferCountToBase: 0, weekendSuitability: 9, weekendSuitabilityEvidence: "Fast direct service and a full weekend within one city base.",
    ManchesterAccessScore: 10, budgetMinGBP: 100, budgetTypicalGBP: 190, budgetMaxGBP: 340, physicalEffort: 3, walkingLevel: 3, cultureScore: 8,
  }),
  weekendRoute({
    id: "man-weekend-birmingham", routeName: "Birmingham Canals, Culture & Jewellery Quarter", shortName: "Birmingham Weekend",
    routeBase: "Birmingham", region: "West Midlands", routeType: "City and culture", weekendRouteType: "City and culture", tripTypes: ["City Break", "Culture", "Food"],
    mainStops: ["Canal Quarter", "Birmingham Museum district", "Jewellery Quarter"], description: "A direct inter-city weekend spanning canals, cultural venues, markets and the Jewellery Quarter.",
    highlights: ["Canal-side centre", "Jewellery Quarter", "Broad food and culture offer"], mainLogisticalDrawback: "City-centre works and event crowds can affect walking routes and prices.",
    officialSourceName: "Visit Birmingham", officialSourceUrl: "https://visitbirmingham.com/whats-on/whats-on-this-weekend/", evidenceNote: "The official weekend listings and district guides support a varied two-night itinerary from a central base.",
    manchesterJourneyTime: { minHours: 1.5, maxHours: 2, label: "1½–2 hours", estimateBasis: "Conservative direct rail band", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 1.75, likelyTransportMode: "Direct train", directConnectionStatus: "direct", majorTransferCountToBase: 0, weekendSuitability: 9, weekendSuitabilityEvidence: "Direct inter-city access with reliable itinerary depth.",
    ManchesterAccessScore: 9, budgetMinGBP: 120, budgetTypicalGBP: 230, budgetMaxGBP: 400, cultureScore: 9, foodScore: 9,
  }),
  weekendRoute({
    id: "man-weekend-lancaster", routeName: "Lancaster Castle & Historic Centre", shortName: "Lancaster",
    minimumDurationDays: 1, idealDurationDays: 2, maximumDurationDays: 3, travelStyles: ["day-trip", "weekend"],
    routeBase: "Lancaster", region: "Lancashire", routeType: "Heritage city", weekendRouteType: "Heritage city", tripTypes: ["City Break", "History", "Slow Travel"],
    mainStops: ["Lancaster Castle", "City Museum", "Canal Quarter"], description: "A small-scale heritage weekend with a direct journey and an easy single-base plan.",
    highlights: ["Lancaster Castle", "Compact historic core", "Canal and riverside walks"], mainLogisticalDrawback: "A full three-day stay may need an optional local excursion.",
    officialSourceName: "Visit Lancaster", officialSourceUrl: "https://visitlancaster.org.uk/", evidenceNote: "The council-backed visitor site presents a compact cluster of heritage sights readily covered in two days.",
    manchesterJourneyTime: { minHours: 0.75, maxHours: 1.25, label: "45–75 minutes", estimateBasis: "Typical direct rail planning band", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 1, likelyTransportMode: "Direct train", directConnectionStatus: "direct", majorTransferCountToBase: 0, weekendSuitability: 9, weekendSuitabilityEvidence: "Short direct access and low logistical load.",
    ManchesterAccessScore: 10, budgetMinGBP: 100, budgetTypicalGBP: 180, budgetMaxGBP: 320, historyScore: 9, relaxationScore: 8,
  }),
  weekendRoute({
    id: "man-weekend-blackpool", routeName: "Blackpool Seafront & Entertainment", shortName: "Blackpool",
    minimumDurationDays: 1, idealDurationDays: 2, maximumDurationDays: 3, travelStyles: ["day-trip", "weekend"],
    routeBase: "Blackpool", region: "Lancashire Coast", routeType: "Seaside", weekendRouteType: "Seaside", tripTypes: ["City Break", "Beach", "Family"],
    mainStops: ["Promenade", "Blackpool Tower", "North Pier"], description: "A straightforward rail weekend using the promenade as the spine for seaside attractions and entertainment.",
    highlights: ["Long level promenade", "Blackpool Tower", "Seasonal shows and illuminations"], mainLogisticalDrawback: "Experience and hotel quality vary sharply by season and location.",
    officialSourceName: "VisitBlackpool", officialSourceUrl: "https://www.visitblackpool.com/", evidenceNote: "The official destination site provides a concentrated weekend-scale attraction offer with rail access from Manchester.",
    manchesterJourneyTime: { minHours: 1.25, maxHours: 1.75, label: "1¼–1¾ hours", estimateBasis: "Conservative direct rail band", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 1.5, likelyTransportMode: "Direct train", directConnectionStatus: "direct", majorTransferCountToBase: 0, weekendSuitability: 8, weekendSuitabilityEvidence: "Direct access and simple promenade-based planning.",
    ManchesterAccessScore: 9, budgetMinGBP: 90, budgetTypicalGBP: 180, budgetMaxGBP: 340, sceneryScore: 5, cultureScore: 5, historyScore: 4, suitableForMum: true,
  }),
  weekendRoute({
    id: "man-weekend-southport", routeName: "Southport Seaside & Lord Street", shortName: "Southport",
    minimumDurationDays: 1, idealDurationDays: 2, maximumDurationDays: 3, travelStyles: ["day-trip", "weekend"],
    routeBase: "Southport", region: "Sefton Coast", routeType: "Seaside", weekendRouteType: "Seaside", tripTypes: ["Beach", "Slow Travel", "Nature"],
    mainStops: ["Lord Street", "Marine Lake", "Seafront"], description: "A relaxed seaside weekend combining the Victorian centre, marine lake and coast.",
    highlights: ["Lord Street", "Marine Lake", "Level coastal promenades"], mainLogisticalDrawback: "The open coast is weather-exposed and some seasonal attractions close early.",
    officialSourceName: "Visit Southport", officialSourceUrl: "https://www.visitsouthport.com/", evidenceNote: "The official destination guide supports a gentle two-day plan around a single walkable seaside base.",
    manchesterJourneyTime: { minHours: 1.25, maxHours: 1.75, label: "1¼–1¾ hours", estimateBasis: "Conservative rail band; stopping pattern varies", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 1.5, likelyTransportMode: "Train", directConnectionStatus: "variable", majorTransferCountToBase: 1, weekendSuitability: 8, weekendSuitabilityEvidence: "Comfortable weekend distance with straightforward rail access.",
    ManchesterAccessScore: 8, budgetMinGBP: 100, budgetTypicalGBP: 190, budgetMaxGBP: 340, natureScore: 6, relaxationScore: 9,
  }),
  weekendRoute({
    id: "man-weekend-shrewsbury", routeName: "Shrewsbury Medieval Streets & River Loop", shortName: "Shrewsbury Weekend",
    routeBase: "Shrewsbury", region: "Shropshire", routeType: "Heritage town", weekendRouteType: "Heritage town", tripTypes: ["City Break", "History", "Slow Travel"],
    mainStops: ["Castle Quarter", "The Quarry", "River Severn loop"], description: "A rail-led heritage break based in Shrewsbury's river-wrapped medieval centre.",
    highlights: ["Medieval street pattern", "The Quarry park", "River Severn walks"], mainLogisticalDrawback: "Cobbles, slopes and historic buildings can create access constraints.",
    officialSourceName: "Original Shrewsbury", officialSourceUrl: "https://originalshrewsbury.co.uk/", evidenceNote: "The official town destination site presents a compact historic core with enough food, heritage and riverside content for two days.",
    manchesterJourneyTime: { minHours: 1.25, maxHours: 2, label: "1¼–2 hours", estimateBasis: "Conservative rail band", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 1.6, likelyTransportMode: "Train", directConnectionStatus: "variable", majorTransferCountToBase: 1, weekendSuitability: 8, weekendSuitabilityEvidence: "Manageable journey and strong single-base heritage itinerary.",
    ManchesterAccessScore: 8, budgetMinGBP: 110, budgetTypicalGBP: 210, budgetMaxGBP: 370, historyScore: 9, walkingLevel: 3, stairsRisk: 3,
  }),
  weekendRoute({
    id: "man-weekend-nottingham", routeName: "Nottingham Castle, Caves & Lace Market", shortName: "Nottingham Weekend",
    routeBase: "Nottingham", region: "Nottinghamshire", routeType: "City and heritage", weekendRouteType: "City and heritage", tripTypes: ["City Break", "History", "Culture"],
    mainStops: ["Nottingham Castle", "Lace Market", "City of Caves"], description: "A culture-and-history weekend focused on the castle area, caves and Lace Market.",
    highlights: ["Nottingham Castle area", "Lace Market", "Cave heritage"], mainLogisticalDrawback: "Some underground attractions involve steps and advance booking.",
    officialSourceName: "Visit Nottinghamshire", officialSourceUrl: "https://www.visit-nottinghamshire.co.uk/", evidenceNote: "The official destination site groups central heritage attractions into a realistic city-weekend programme.",
    manchesterJourneyTime: { minHours: 1.75, maxHours: 2.5, label: "1¾–2½ hours", estimateBasis: "Conservative rail band; service pattern varies", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 2.1, likelyTransportMode: "Train", directConnectionStatus: "variable", majorTransferCountToBase: 1, weekendSuitability: 7, weekendSuitabilityEvidence: "Feasible within two nights but more sensitive to train choice than nearer cities.",
    ManchesterAccessScore: 7, budgetMinGBP: 120, budgetTypicalGBP: 230, budgetMaxGBP: 410, historyScore: 9, cultureScore: 8, stairsRisk: 3,
  }),
  weekendRoute({
    id: "man-weekend-hull", routeName: "Hull Old Town & Maritime Quarter", shortName: "Hull Weekend",
    routeBase: "Hull", region: "East Yorkshire", routeType: "Maritime city", weekendRouteType: "Maritime city", tripTypes: ["City Break", "History", "Culture"],
    mainStops: ["Old Town", "Museum Quarter", "Marina"], description: "A maritime city weekend based around Hull's Old Town, museums and marina.",
    highlights: ["Free Museum Quarter", "Historic Old Town", "Marina and waterfront"], mainLogisticalDrawback: "The longer cross-Pennine journey is vulnerable to disruption.",
    officialSourceName: "Visit Hull", officialSourceUrl: "https://www.visithull.com/", evidenceNote: "The official city guide shows a dense central maritime and museum offer suitable for a two-night visit.",
    manchesterJourneyTime: { minHours: 2, maxHours: 2.75, label: "2–2¾ hours", estimateBasis: "Conservative cross-Pennine rail band", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 2.4, likelyTransportMode: "Train", directConnectionStatus: "variable", majorTransferCountToBase: 1, fridayEveningFeasible: "uncertain", weekendSuitability: 7, weekendSuitabilityEvidence: "Good Saturday-to-Sunday plan; Friday usefulness depends on the selected service.",
    ManchesterAccessScore: 7, budgetMinGBP: 110, budgetTypicalGBP: 210, budgetMaxGBP: 380, historyScore: 8, cultureScore: 8,
  }),
  weekendRoute({
    id: "man-weekend-scarborough", routeName: "Scarborough Seafront, Castle & Old Town", shortName: "Scarborough Weekend",
    routeBase: "Scarborough", region: "North Yorkshire Coast", routeType: "Seaside heritage", weekendRouteType: "Seaside heritage", tripTypes: ["Beach", "History", "Slow Travel"],
    mainStops: ["South Bay", "Scarborough Castle", "Old Town"], description: "A two-night coastal break using central Scarborough as the base for bays, castle and old town.",
    highlights: ["Two contrasting bays", "Castle headland", "Traditional seaside townscape"], mainLogisticalDrawback: "Hills between the station, castle and bays increase walking effort.",
    officialSourceName: "TransPennine Express – Scarborough", officialSourceUrl: "https://www.tpexpress.co.uk/explore-the-north-and-scotland/destinations/scarborough", evidenceNote: "The operator's official destination page supports rail-based visits; the journey band keeps the plan conservative.",
    manchesterJourneyTime: { minHours: 2.25, maxHours: 3, label: "2¼–3 hours", estimateBasis: "Conservative rail band; through-service pattern varies", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 2.6, likelyTransportMode: "Train", directConnectionStatus: "variable", majorTransferCountToBase: 1, fridayEveningFeasible: "uncertain", weekendSuitability: 7, weekendSuitabilityEvidence: "Strong two-day destination, but Friday arrival comfort is service-dependent.",
    ManchesterAccessScore: 7, budgetMinGBP: 130, budgetTypicalGBP: 250, budgetMaxGBP: 440, physicalEffort: 3, walkingLevel: 3, stairsRisk: 3, sceneryScore: 8, relaxationScore: 8,
  }),
  weekendRoute({
    id: "man-weekend-durham", routeName: "Durham Cathedral City", shortName: "Durham Weekend",
    routeBase: "Durham", region: "County Durham", routeType: "Heritage city", weekendRouteType: "Heritage city", tripTypes: ["City Break", "History", "Culture"],
    mainStops: ["Durham Cathedral", "Castle peninsula", "River Wear"], description: "A compact cathedral-city weekend with riverside scenery and a single central base.",
    highlights: ["Cathedral and castle peninsula", "River Wear loop", "Compact historic centre"], mainLogisticalDrawback: "The station and peninsula involve notable slopes.",
    officialSourceName: "This is Durham", officialSourceUrl: "https://www.thisisdurham.com/explore-durham/durham-city", evidenceNote: "The official destination guide concentrates the cathedral, castle and riverside into a strong two-day itinerary.",
    manchesterJourneyTime: { minHours: 2.25, maxHours: 3, label: "2¼–3 hours", estimateBasis: "Conservative direct/cross-Pennine rail band", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 2.6, likelyTransportMode: "Train", directConnectionStatus: "variable", majorTransferCountToBase: 1, fridayEveningFeasible: "uncertain", weekendSuitability: 8, weekendSuitabilityEvidence: "Compact destination offsets the longer journey; Saturday morning is straightforward.",
    ManchesterAccessScore: 8, budgetMinGBP: 130, budgetTypicalGBP: 250, budgetMaxGBP: 440, historyScore: 10, cultureScore: 9, physicalEffort: 3, walkingLevel: 3, stairsRisk: 3,
  }),
  weekendRoute({
    id: "man-weekend-newcastle", routeName: "NewcastleGateshead City Weekend", shortName: "Newcastle Weekend",
    routeBase: "Newcastle", region: "Tyne and Wear", routeType: "City and culture", weekendRouteType: "City and culture", tripTypes: ["City Break", "Culture", "Food"],
    mainStops: ["Quayside", "Grainger Town", "Gateshead cultural quarter"], description: "A lively two-night city break built around the Quayside, central architecture and Gateshead venues.",
    highlights: ["Tyne bridges and Quayside", "Grainger Town", "Gateshead arts venues"], mainLogisticalDrawback: "A longer Friday journey can leave little usable first evening.",
    officialSourceName: "NewcastleGateshead Initiative", officialSourceUrl: "https://newcastlegateshead.com/", evidenceNote: "The official destination site provides a substantial city-break offer around well-connected central districts.",
    manchesterJourneyTime: { minHours: 2.5, maxHours: 3.25, label: "2½–3¼ hours", estimateBasis: "Conservative cross-Pennine rail band", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 2.9, likelyTransportMode: "Train", directConnectionStatus: "direct", majorTransferCountToBase: 0, fridayEveningFeasible: "uncertain", weekendSuitability: 8, weekendSuitabilityEvidence: "Direct journey and rich two-day programme; Friday comfort varies.",
    ManchesterAccessScore: 8, budgetMinGBP: 140, budgetTypicalGBP: 280, budgetMaxGBP: 480, cultureScore: 9, foodScore: 9,
  }),
  weekendRoute({
    id: "man-weekend-edinburgh", routeName: "Edinburgh Old Town & New Town", shortName: "Edinburgh Weekend",
    imageUrl: localRouteImage("edinburgh-old-town.svg"), imageAlt: "Stylised Edinburgh Old Town skyline with the castle ridge and layered stone buildings", imageCredit: "Original local illustration",
    routeBase: "Edinburgh", region: "Scotland", routeType: "Capital city", weekendRouteType: "Capital city", tripTypes: ["City Break", "History", "Culture"], countries: ["United Kingdom"],
    mainStops: ["Old Town", "New Town", "Calton Hill"], description: "A high-content capital weekend with direct rail options and a central single-base itinerary.",
    highlights: ["Old and New Towns", "National museums", "Calton Hill viewpoints"], mainLogisticalDrawback: "The journey is long for two days and central accommodation can be costly.",
    officialSourceName: "Forever Edinburgh", officialSourceUrl: "https://edinburgh.org/things-to-do/itineraries/a-weekend-in-edinburgh/", evidenceNote: "The official destination organisation publishes a dedicated weekend itinerary, while timing remains a planning estimate.",
    manchesterJourneyTime: { minHours: 3.25, maxHours: 4, label: "3¼–4 hours", estimateBasis: "Conservative direct rail band", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 3.6, likelyTransportMode: "Direct train", directConnectionStatus: "direct", majorTransferCountToBase: 0, fridayEveningFeasible: "uncertain", weekendSuitability: 7, weekendSuitabilityEvidence: "Excellent weekend content, ranked below nearer cities because of journey length.",
    ManchesterAccessScore: 7, budgetMinGBP: 180, budgetTypicalGBP: 360, budgetMaxGBP: 650, physicalEffort: 3, walkingLevel: 4, stairsRisk: 4, cultureScore: 10, historyScore: 10, suitableForMum: false,
  }),
  weekendRoute({
    id: "man-weekend-carlisle", routeName: "Carlisle Castle & Border History", shortName: "Carlisle Weekend",
    routeBase: "Carlisle", region: "Cumbria", routeType: "Heritage city", weekendRouteType: "Heritage city", tripTypes: ["City Break", "History"],
    mainStops: ["Carlisle Castle", "Cathedral", "Tullie"], description: "A direct-rail border-city break with castle, cathedral and museum content close to the centre.",
    highlights: ["Carlisle Castle", "Border history", "Compact cathedral quarter"], mainLogisticalDrawback: "Two days is ample unless adding a weather- and timetable-dependent excursion.",
    officialSourceName: "Discover Carlisle", officialSourceUrl: "https://www.discovercarlisle.co.uk/wp-content/uploads/2025/02/3-day-A-Weekend-in-Carlisle.pdf", evidenceNote: "The council destination service publishes a specific multi-day Carlisle weekend guide.",
    manchesterJourneyTime: { minHours: 2, maxHours: 2.5, label: "2–2½ hours", estimateBasis: "Conservative direct rail band", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 2.2, likelyTransportMode: "Direct train", directConnectionStatus: "direct", majorTransferCountToBase: 0, weekendSuitability: 8, weekendSuitabilityEvidence: "Direct journey and compact heritage itinerary.",
    ManchesterAccessScore: 8, budgetMinGBP: 110, budgetTypicalGBP: 210, budgetMaxGBP: 380, historyScore: 9,
  }),
  weekendRoute({
    id: "man-weekend-harrogate-knaresborough", routeName: "Harrogate & Knaresborough", shortName: "Harrogate & Knaresborough",
    routeBase: "Harrogate", region: "North Yorkshire", routeType: "Spa town pairing", weekendRouteType: "Spa town pairing", tripTypes: ["Slow Travel", "History", "Food"],
    mainStops: ["Harrogate", "Knaresborough"], description: "A two-base-in-one weekend using Harrogate for the hotel and a short local rail trip to Knaresborough.",
    highlights: ["Harrogate gardens and spa heritage", "Knaresborough viaduct views", "Easy local rail link"], mainLogisticalDrawback: "Manchester services may require a Leeds change and Sunday frequencies need checking.",
    officialSourceName: "Visit North Yorkshire – Harrogate", officialSourceUrl: "https://visitharrogate.co.uk/places/harrogate", evidenceNote: "The official destination site presents complementary attractions in two nearby, rail-linked towns.",
    manchesterJourneyTime: { minHours: 1.75, maxHours: 2.5, label: "1¾–2½ hours", estimateBasis: "Conservative rail band with up to one major change", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 2.1, likelyTransportMode: "Train", directConnectionStatus: "change-required", majorTransferCountToBase: 1, localConnectionsRequired: true, fridayEveningFeasible: "uncertain", weekendSuitability: 8, weekendSuitabilityEvidence: "Good paired itinerary with one manageable base transfer.",
    ManchesterAccessScore: 8, budgetMinGBP: 140, budgetTypicalGBP: 270, budgetMaxGBP: 470, relaxationScore: 9, foodScore: 8,
  }),
  weekendRoute({
    id: "man-weekend-hebden-haworth", routeName: "Hebden Bridge & Haworth", shortName: "Hebden Bridge & Haworth",
    routeBase: "Hebden Bridge", region: "West Yorkshire", routeType: "Market town pairing", weekendRouteType: "Market town pairing", tripTypes: ["Slow Travel", "History", "Nature"],
    mainStops: ["Hebden Bridge", "Haworth", "Calder Valley"], description: "A Calder Valley weekend based in Hebden Bridge with a bus-linked Haworth day visit.",
    highlights: ["Hebden Bridge independent centre", "Haworth literary heritage", "Valley scenery"], mainLogisticalDrawback: "The Haworth link adds a local bus dependency and steep streets.",
    officialSourceName: "Visit Calderdale", officialSourceUrl: "https://www.visitcalderdale.com/", evidenceNote: "Official local tourism information plus the council's Hebden-to-Haworth material support the pairing without treating the whole valley as one route.",
    manchesterJourneyTime: { minHours: 0.75, maxHours: 1.25, label: "45–75 minutes to Hebden Bridge", estimateBasis: "Direct rail to base; local bus for Haworth", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 1, likelyTransportMode: "Direct train plus local bus", directConnectionStatus: "direct", majorTransferCountToBase: 0, localConnectionsRequired: true, fridayEveningFeasible: true, weekendSuitability: 8, weekendSuitabilityEvidence: "Very short base journey; local excursion adds moderate complexity.",
    ManchesterAccessScore: 9, budgetMinGBP: 110, budgetTypicalGBP: 220, budgetMaxGBP: 390, physicalEffort: 3, walkingLevel: 4, stairsRisk: 4, sceneryScore: 8, historyScore: 8, suitableForMum: false,
  }),
  weekendRoute({
    id: "man-weekend-buxton-bakewell", routeName: "Buxton Base with Bakewell Day Trip", shortName: "Buxton & Bakewell",
    routeBase: "Buxton", region: "Peak District", routeType: "National park towns by public transport", weekendRouteType: "National park towns by public transport", tripTypes: ["Nature", "Slow Travel", "History"],
    mainStops: ["Buxton", "Bakewell"], description: "A specific Peak District plan using rail-connected Buxton as the base and a daytime bus to Bakewell.",
    highlights: ["Buxton spa architecture", "Bakewell riverside", "No-car national park access"], mainLogisticalDrawback: "The Bakewell bus is a material timetable dependency, especially on Sundays.",
    officialSourceName: "Peak District National Park – bus routes", officialSourceUrl: "https://www.peakdistrict.gov.uk/visiting/planning-your-visit/publictransport/peak-district-bus-routes", evidenceNote: "The National Park Authority documents the relevant public-transport network; Buxton is used as a concrete rail base rather than modelling the entire park.",
    manchesterJourneyTime: { minHours: 1, maxHours: 1.5, label: "1–1½ hours to Buxton", estimateBasis: "Direct rail to base; local bus for Bakewell", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 1.25, likelyTransportMode: "Direct train plus local bus", directConnectionStatus: "direct", majorTransferCountToBase: 0, localConnectionsRequired: true, fridayEveningFeasible: true, sundayEveningReturnFeasible: "uncertain", weekendSuitability: 7, weekendSuitabilityEvidence: "Easy base access, with suitability reduced by the Sunday bus dependency.",
    ManchesterAccessScore: 9, budgetMinGBP: 110, budgetTypicalGBP: 220, budgetMaxGBP: 390, typicalTransferLevel: "medium", physicalEffort: 3, walkingLevel: 3, sceneryScore: 8, natureScore: 8,
  }),
  weekendRoute({
    id: "man-weekend-edale-castleton", routeName: "Edale & Castleton Hope Valley", shortName: "Edale & Castleton",
    routeBase: "Edale", region: "Peak District", routeType: "Walking bases by public transport", weekendRouteType: "Walking bases by public transport", tripTypes: ["Hiking", "Nature", "Scenic Railway"],
    mainStops: ["Edale", "Castleton", "Hope Valley"], description: "A specific Hope Valley walking weekend using the Manchester–Sheffield railway and local links.",
    highlights: ["Edale valley", "Castleton village", "Car-free Hope Valley access"], mainLogisticalDrawback: "Rural evening and Sunday links are vulnerable to timetable changes and weather.",
    officialSourceName: "Peak District National Park – Edale", officialSourceUrl: "https://www.peakdistrict.gov.uk/visiting/visitor-centres/edale", evidenceNote: "The National Park Authority identifies Edale as a public-transport visitor base; Castleton remains a distinct local connection rather than a generic park record.",
    manchesterJourneyTime: { minHours: 0.75, maxHours: 1.5, label: "45–90 minutes to Edale", estimateBasis: "Direct Hope Valley rail band; local connection for Castleton", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 1.1, likelyTransportMode: "Direct train plus local bus", directConnectionStatus: "direct", majorTransferCountToBase: 0, localConnectionsRequired: true, fridayEveningFeasible: "uncertain", sundayEveningReturnFeasible: "uncertain", weekendSuitability: 6, weekendSuitabilityEvidence: "Short base journey, but rural timing and walking conditions require verification.",
    ManchesterAccessScore: 9, budgetMinGBP: 100, budgetTypicalGBP: 210, budgetMaxGBP: 380, typicalTransferLevel: "medium", physicalEffort: 4, walkingLevel: 5, stairsRisk: 4, comfortLevel: 2, weatherRisk: 4, natureScore: 10, sceneryScore: 9, suitableForOlderTraveller: false, suitableForMum: false,
  }),
  weekendRoute({
    id: "man-weekend-hathersage-stanage", routeName: "Hathersage & Stanage Edge", shortName: "Hathersage & Stanage",
    routeBase: "Hathersage", region: "Peak District", routeType: "Walking base", weekendRouteType: "Walking base", tripTypes: ["Hiking", "Nature"],
    mainStops: ["Hathersage", "Stanage Edge", "North Lees"], description: "A rail-accessible Hathersage base with a weather-dependent walking day around Stanage and North Lees.",
    highlights: ["Direct Hope Valley rail access", "Stanage Edge scenery", "Hathersage village base"], mainLogisticalDrawback: "Reaching Stanage and completing the walk requires fitness, navigation and suitable weather.",
    officialSourceName: "Peak District National Park – Stanage and North Lees", officialSourceUrl: "https://www.peakdistrict.gov.uk/visiting/places-to-visit/stanage-and-north-lees", evidenceNote: "The National Park Authority documents this specific landscape and access context; it is modelled as a Hathersage walking base.",
    manchesterJourneyTime: { minHours: 0.75, maxHours: 1.5, label: "45–90 minutes to Hathersage", estimateBasis: "Direct Hope Valley rail band", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 1.1, likelyTransportMode: "Direct train plus walking/local taxi", directConnectionStatus: "direct", majorTransferCountToBase: 0, localConnectionsRequired: true, fridayEveningFeasible: true, weekendSuitability: 6, weekendSuitabilityEvidence: "Easy rail base but high physical and weather sensitivity.",
    ManchesterAccessScore: 9, budgetMinGBP: 100, budgetTypicalGBP: 210, budgetMaxGBP: 390, physicalEffort: 5, walkingLevel: 5, stairsRisk: 4, comfortLevel: 2, weatherRisk: 4, natureScore: 10, sceneryScore: 10, suitableForOlderTraveller: false, suitableForMum: false, carDependency: "useful",
  }),
  weekendRoute({
    id: "man-weekend-bakewell-chatsworth-drive", routeName: "Bakewell & Chatsworth – Driving Variant", shortName: "Bakewell & Chatsworth (car)",
    routeBase: "Bakewell", region: "Peak District", routeType: "Driving-based heritage and landscape", weekendRouteType: "Driving-based heritage and landscape", tripTypes: ["History", "Nature", "Road Trip"],
    mainStops: ["Bakewell", "Chatsworth", "Monsal Head"], description: "A driving-dependent Peak District weekend based in Bakewell with Chatsworth and an optional viewpoint stop.",
    highlights: ["Bakewell base", "Chatsworth estate", "Flexible countryside stops"], mainLogisticalDrawback: "A car is required for this version and weekend congestion or parking can be significant.",
    officialSourceName: "Peak District National Park – public transport planning", officialSourceUrl: "https://www.peakdistrict.gov.uk/visiting/planning-your-visit/publictransport", evidenceNote: "This is deliberately separated from the public-transport Buxton variant because practical access and timing differ materially.",
    manchesterJourneyTime: { minHours: 1.25, maxHours: 2, label: "1¼–2 hours by car", estimateBasis: "Conservative off-peak driving band; traffic can exceed it", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 1.6, likelyTransportMode: "Car", directConnectionStatus: "direct", majorTransferCountToBase: 0, carDependency: "required", drivingRequired: true, trainPossible: false, fridayEveningFeasible: true, weekendSuitability: 7, weekendSuitabilityEvidence: "Flexible weekend plan for drivers, but congestion and parking reduce reliability.",
    ManchesterAccessScore: 8, budgetMinGBP: 150, budgetTypicalGBP: 280, budgetMaxGBP: 480, typicalTransferLevel: "low", physicalEffort: 3, walkingLevel: 3, natureScore: 9, sceneryScore: 9, historyScore: 9,
  }),
  weekendRoute({
    id: "man-weekend-windermere-ambleside", routeName: "Windermere & Ambleside by Rail and Bus", shortName: "Windermere & Ambleside",
    imageUrl: localRouteImage("windermere-ambleside.svg"), imageAlt: "Stylised Lake Windermere scene with green fells, calm water and a small passenger boat", imageCredit: "Original local illustration",
    routeBase: "Windermere", region: "Lake District", routeType: "Lake towns by public transport", weekendRouteType: "Lake towns by public transport", tripTypes: ["Nature", "Slow Travel", "Boat"],
    mainStops: ["Windermere", "Ambleside", "Bowness"], description: "A specific Lake District public-transport weekend using Windermere as the rail base and local bus or boat links.",
    highlights: ["Windermere lake shore", "Ambleside base facilities", "Bus and boat options"], mainLogisticalDrawback: "At least one rail change plus local transport makes Friday evening less comfortable.",
    officialSourceName: "Lake District National Park – Windermere and Ambleside", officialSourceUrl: "https://lakedistrict.gov.uk/explore/places-to-go/explore-windermere-and-ambleside/getting-to-and-around-windermere-and-ambleside/", evidenceNote: "The National Park Authority explicitly describes getting to and around these specific linked bases without a car.",
    manchesterJourneyTime: { minHours: 1.75, maxHours: 2.75, label: "1¾–2¾ hours to Windermere", estimateBasis: "Rail with up to one major change; local bus/boat extra", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 2.2, likelyTransportMode: "Train plus local bus/boat", directConnectionStatus: "change-required", majorTransferCountToBase: 1, localConnectionsRequired: true, fridayEveningFeasible: "uncertain", weekendSuitability: 7, weekendSuitabilityEvidence: "Strong Saturday start; Friday feasibility is connection-dependent.",
    ManchesterAccessScore: 8, budgetMinGBP: 160, budgetTypicalGBP: 310, budgetMaxGBP: 540, typicalTransferLevel: "medium", physicalEffort: 3, walkingLevel: 3, natureScore: 9, sceneryScore: 10, relaxationScore: 9,
  }),
  weekendRoute({
    id: "man-weekend-keswick", routeName: "Keswick & Derwentwater", shortName: "Keswick Weekend",
    routeBase: "Keswick", region: "Lake District", routeType: "Lake town by rail and bus", weekendRouteType: "Lake town by rail and bus", tripTypes: ["Nature", "Hiking", "Boat"],
    mainStops: ["Keswick", "Derwentwater", "Borrowdale viewpoints"], description: "A Keswick-based weekend reached via Penrith, with lake, town and optional lower-level walking.",
    highlights: ["Derwentwater", "Keswick market town", "Choice of gentle or strenuous outings"], mainLogisticalDrawback: "The Penrith–Keswick bus is essential and constrains late Friday and Sunday timing.",
    officialSourceName: "Visit Lake District – Keswick", officialSourceUrl: "https://www.visitlakedistrict.com/explore/keswick", evidenceNote: "The official destination site supports Keswick as a distinct base; rail-to-bus feasibility is treated separately from Windermere.",
    manchesterJourneyTime: { minHours: 2, maxHours: 3.25, label: "2–3¼ hours via Penrith", estimateBasis: "Rail plus one essential bus connection", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 2.6, likelyTransportMode: "Train plus bus", directConnectionStatus: "change-required", majorTransferCountToBase: 1, localConnectionsRequired: true, fridayEveningFeasible: false, sundayEveningReturnFeasible: "uncertain", weekendSuitability: 6, weekendSuitabilityEvidence: "Saturday morning is realistic; a post-work Friday start is not treated as practical and Sunday needs live checking.",
    ManchesterAccessScore: 7, budgetMinGBP: 150, budgetTypicalGBP: 300, budgetMaxGBP: 520, typicalTransferLevel: "medium", physicalEffort: 3, walkingLevel: 3, weatherRisk: 4, natureScore: 10, sceneryScore: 10, relaxationScore: 8, carDependency: "useful",
  }),
  weekendRoute({
    id: "man-weekend-llandudno-conwy", routeName: "Llandudno & Conwy", shortName: "Llandudno & Conwy",
    routeBase: "Llandudno", region: "North Wales Coast", routeType: "Coastal town pairing", weekendRouteType: "Coastal town pairing", tripTypes: ["Beach", "History", "Slow Travel"], countries: ["United Kingdom"],
    mainStops: ["Llandudno", "Conwy", "Great Orme"], description: "A North Wales coast weekend based in Llandudno with a short rail trip to Conwy.",
    highlights: ["Llandudno promenade", "Conwy Castle and walls", "Great Orme options"], mainLogisticalDrawback: "Through trains vary and the Great Orme can be weather-dependent.",
    officialSourceName: "Visit Wales – Llandudno and Colwyn Bay", officialSourceUrl: "https://www.visitwales.com/destinations/north-wales/llandudno-colwyn-bay", evidenceNote: "Visit Wales presents Llandudno as a specific coast base, with nearby Conwy reached by a short local connection.",
    manchesterJourneyTime: { minHours: 1.75, maxHours: 2.75, label: "1¾–2¾ hours", estimateBasis: "Conservative rail band with zero or one major change", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 2.2, likelyTransportMode: "Train", directConnectionStatus: "variable", majorTransferCountToBase: 1, localConnectionsRequired: true, fridayEveningFeasible: "uncertain", weekendSuitability: 8, weekendSuitabilityEvidence: "Strong two-town itinerary with manageable rail access.",
    ManchesterAccessScore: 8, budgetMinGBP: 130, budgetTypicalGBP: 250, budgetMaxGBP: 440, physicalEffort: 3, walkingLevel: 3, stairsRisk: 3, sceneryScore: 9, historyScore: 9, relaxationScore: 8,
  }),
  weekendRoute({
    id: "man-weekend-betws-conwy-valley", routeName: "Betws-y-Coed & Conwy Valley", shortName: "Betws-y-Coed Weekend",
    routeBase: "Betws-y-Coed", region: "Conwy Valley, North Wales", routeType: "Rural rail base", weekendRouteType: "Rural rail base", tripTypes: ["Nature", "Hiking", "Scenic Railway"],
    mainStops: ["Betws-y-Coed", "Conwy Valley", "Swallow Falls area"], description: "A specific rural North Wales weekend based in Betws-y-Coed and reached by the Conwy Valley line.",
    highlights: ["Forest and river scenery", "Conwy Valley rail journey", "Walks from a defined village base"], mainLogisticalDrawback: "Infrequent rural services make late Friday and Sunday-evening plans fragile.",
    officialSourceName: "Visit Wales – attractions by public transport", officialSourceUrl: "https://traveltrade.visitwales.com/fact-sheets/more-inspiration/visit-north-wales-attractions-public-transport-routes", evidenceNote: "Visit Wales documents public-transport access to North Wales attractions; this record uses Betws-y-Coed rather than the whole region.",
    manchesterJourneyTime: { minHours: 2.5, maxHours: 3.75, label: "2½–3¾ hours", estimateBasis: "Rail with one major interchange and a rural connecting service", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 3.1, likelyTransportMode: "Train", directConnectionStatus: "change-required", majorTransferCountToBase: 1, fridayEveningFeasible: false, sundayEveningReturnFeasible: "uncertain", weekendSuitability: 6, weekendSuitabilityEvidence: "Saturday departure works; a post-work Friday start is not treated as practical and Sunday depends on the rural timetable.",
    ManchesterAccessScore: 6, budgetMinGBP: 130, budgetTypicalGBP: 260, budgetMaxGBP: 450, typicalTransferLevel: "medium", physicalEffort: 4, walkingLevel: 4, stairsRisk: 3, weatherRisk: 4, natureScore: 10, sceneryScore: 10, suitableForMum: false,
  }),
  weekendRoute({
    id: "man-weekend-northumberland-coast", routeName: "Newcastle Base with Alnwick or Bamburgh Coast Day", shortName: "Newcastle & Northumberland Coast",
    routeBase: "Newcastle", region: "Northumberland Coast", routeType: "City base with public-transport coast day", weekendRouteType: "City base with public-transport coast day", tripTypes: ["Nature", "History", "City Break"],
    mainStops: ["Newcastle", "Alnwick or Bamburgh", "Northumberland coast"], description: "A Newcastle hotel base with one carefully chosen coast day, avoiding an unreliable Manchester-facing rural base.",
    highlights: ["Simple city hotel base", "Choice of castle or coast focus", "No car required for the planned variant"], mainLogisticalDrawback: "The coast day has long local bus legs and must be checked against the current Sunday timetable.",
    officialSourceName: "Visit Northumberland – getting around", officialSourceUrl: "https://www.visitnorthumberland.com/travel-tips/while-youre-here/getting-around", evidenceNote: "The official destination site supports public-transport exploration; Newcastle is retained as the base because a direct Manchester-to-coast weekend is not robust.",
    manchesterJourneyTime: { minHours: 2.5, maxHours: 3.25, label: "2½–3¼ hours to Newcastle", estimateBasis: "Direct rail to base; long local bus for coast day", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 2.9, likelyTransportMode: "Direct train plus local bus", directConnectionStatus: "direct", majorTransferCountToBase: 0, localConnectionsRequired: true, fridayEveningFeasible: "uncertain", sundayEveningReturnFeasible: true, weekendSuitability: 6, weekendSuitabilityEvidence: "The city base keeps transfers low, but the coast day remains timetable-sensitive.",
    ManchesterAccessScore: 7, budgetMinGBP: 160, budgetTypicalGBP: 310, budgetMaxGBP: 540, typicalTransferLevel: "medium", physicalEffort: 3, walkingLevel: 3, weatherRisk: 4, natureScore: 9, sceneryScore: 9, historyScore: 9,
  }),
  weekendRoute({
    id: "man-weekend-london", routeName: "London Museums, Markets & West End", shortName: "London Weekend",
    routeBase: "London", region: "Greater London", routeType: "Capital city", weekendRouteType: "Capital city", tripTypes: ["City Break", "Culture", "Food"],
    mainStops: ["Central museums", "West End", "One market district"], description: "A direct-rail capital weekend focused on a deliberately limited set of central districts.",
    highlights: ["Major free museums", "Markets and neighbourhood food", "West End entertainment"], mainLogisticalDrawback: "High accommodation costs and extensive local travel can make a short visit tiring.",
    officialSourceName: "Visit London", officialSourceUrl: "https://www.visitlondon.com/things-to-do/weekends-in-london", evidenceNote: "The official destination site provides dedicated weekend guidance; the plan stays within selected central districts.",
    manchesterJourneyTime: { minHours: 2.1, maxHours: 2.75, label: "2–2¾ hours", estimateBasis: "Conservative direct inter-city rail band", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 2.4, likelyTransportMode: "Direct train plus urban transit", directConnectionStatus: "direct", majorTransferCountToBase: 0, localConnectionsRequired: true, weekendSuitability: 8, weekendSuitabilityEvidence: "Frequent direct access and exceptional itinerary depth, tempered by cost and scale.",
    ManchesterAccessScore: 8, budgetMinGBP: 190, budgetTypicalGBP: 390, budgetMaxGBP: 700, physicalEffort: 3, walkingLevel: 4, cultureScore: 10, historyScore: 10, foodScore: 10, suitableForMum: false,
  }),
  weekendRoute({
    id: "man-weekend-bristol", routeName: "Bristol Harbourside & Old City", shortName: "Bristol Weekend",
    routeBase: "Bristol", region: "South West England", routeType: "Harbour city", weekendRouteType: "Harbour city", tripTypes: ["City Break", "Culture", "Food"],
    mainStops: ["Harbourside", "Old City", "Clifton option"], description: "A harbour-city weekend using a central base for maritime heritage, food and street culture.",
    highlights: ["Harbourside", "Old City", "Independent food and culture"], mainLogisticalDrawback: "The long journey and Bristol's hills reduce the comfort of a two-day trip.",
    officialSourceName: "Visit Bristol", officialSourceUrl: "https://visitbristol.co.uk/", evidenceNote: "The official destination site provides enough central harbour and city content for a two-night visit, though journey time lowers its ranking.",
    manchesterJourneyTime: { minHours: 3, maxHours: 3.75, label: "3–3¾ hours", estimateBasis: "Conservative direct/inter-city rail band", checkedDate: "2026-07-17" }, approximateManchesterToStartHours: 3.4, likelyTransportMode: "Train", directConnectionStatus: "variable", majorTransferCountToBase: 1, fridayEveningFeasible: "uncertain", weekendSuitability: 6, weekendSuitabilityEvidence: "A valid Saturday-to-Sunday city break, but long for a Friday evening start.",
    ManchesterAccessScore: 6, budgetMinGBP: 150, budgetTypicalGBP: 300, budgetMaxGBP: 520, physicalEffort: 3, walkingLevel: 4, stairsRisk: 3, cultureScore: 9, foodScore: 9, suitableForMum: false,
  }),
];
